export enum Role {
  "ADMIN" = "ADMIN",
  "SUPER_ADMIN" = "SUPER_ADMIN",
  "DRIVER" = "DRIVER",
  "BROKER" = "BROKER",
  "COMBINATION_USER" = "COMBINATION_USER",
  "COMPANY" = "COMPANY",
  "PUBLIC_USER" = "PUBLIC_USER",
  "VERIFIED_DRIVER" = "VERIFIED_DRIVER",
  "VERIFIED_BROKER" = "VERIFIED_BROKER",
  "VERIFIED_COMBINATION_USER" = "VERIFIED_COMBINATION_USER",
  "VERIFIED_COMPANY" = "VERIFIED_COMPANY",
  "TESTING" = "TESTING",
}